### ISSUE TITLE
Unable to upload projects converted from 1.0 to 2.0 in FE

### ISSUE THREAD

**Issue by robynstuart** [optimamodel/Optima#771]
To replicate:

1. Convert a project from 1.0 to 2.0. An example of a script to do this is here: https://github.com/optimamodel/analyses/blob/master/ethiopia/convertethiopia.py
2. In FE, select Manage project -> Upload new project and select the converted project file that you just created for upload 

_Expected result:_
Project should upload

_Actual result:_
Error message as below, presumably from presence of NaNs in cost-coverage data

```
Traceback (most recent call last):
  File "/opt/optima/server/webapp/utils.py", line 63, in _report_exception
    return api_call(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 679, in wrapper
    resp = f(*args, **kwargs)
  File "/opt/optima/server/webapp/resources/project.py", line 782, in post
    project_entry.restore(project_instance)
  File "/opt/optima/server/webapp/dbmodels.py", line 283, in restore
    progset_record.restore(progset, program_list)
  File "/opt/optima/server/webapp/dbmodels.py", line 768, in restore
    p = update_or_create_program(self.project.id, self.id, program_name, program, active)
  File "/opt/optima/server/webapp/utils.py", line 459, in update_or_create_program
    progset_id=progset_id
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2367, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2228, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2437, in __iter__
    self.session._autoflush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1208, in _autoflush
    util.raise_from_cause(e)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1198, in _autoflush
    self.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1919, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2001, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 602, in _emit_insert_statements
    execute(statement, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
DataError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (DataError) invalid input syntax for type json
LINE 1: ... '{"hivstatus": "allstates", "pregnant": false}', '[{"cost":...
                                                             ^
DETAIL:  Token "NaN" is invalid.
CONTEXT:  JSON data, line 1: [{"cost": NaN...
 'INSERT INTO programs (progset_id, project_id, category, name, short_name, pars, active, targetpops, criteria, costcov, ccopars, created, updated) VALUES (%(progset_id)s, %(project_id)s, %(category)s, %(name)s, %(short_name)s, %(pars)s, %(active)s, %(targetpops)s, %(criteria)s, %(costcov)s, %(ccopars)s, %(created)s, %(updated)s) RETURNING programs.id' {'category': 'No category', 'updated': datetime.datetime(2016, 4, 8, 9, 17, 17, 261885, tzinfo=tzutc()), 'name': '', 'short_name': u'VMMC', 'created': datetime.datetime(2016, 4, 8, 9, 17, 17, 261870, tzinfo=tzutc()), 'ccopars': '{"saturation": [[0.9, 0.9]], "t": [2016.0], "unitcost": [[0.0035059805785287715, 0.0035059805785287715]]}', 'targetpops': ['tot'], 'costcov': '[{"cost": NaN, "coverage": NaN, "year": 2000.0}, {"cost": NaN, "coverage": NaN, "year": 2001.0}, {"cost": NaN, "coverage": NaN, "year": 2002.0}, {"cost": NaN, "coverage": NaN, "year": 2003.0}, {"cost": NaN, "coverage": NaN, "year": 2004.0}, {"cost": NaN, "coverage": NaN, "year": 2005.0}, {"cost": NaN, "coverage": NaN, "year": 2006.0}, {"cost": NaN, "coverage": NaN, "year": 2007.0}, {"cost": NaN, "coverage": NaN, "year": 2008.0}, {"cost": NaN, "coverage": NaN, "year": 2009.0}, {"cost": NaN, "coverage": NaN, "year": 2010.0}, {"cost": NaN, "coverage": 0.4223, "year": 2011.0}, {"cost": 257545.96796263542, "coverage": 0.638172, "year": 2012.0}, {"cost": NaN, "coverage": 0.840624, "year": 2013.0}, {"cost": 441543.4699279, "coverage": NaN, "year": 2014.0}, {"cost": NaN, "coverage": NaN, "year": 2015.0}, {"cost": NaN, "coverage": NaN, "year": 2016.0}, {"cost": NaN, "coverage": NaN, "year": 2017.0}, {"cost": NaN, "coverage": NaN, "year": 2018.0}, {"cost": NaN, "coverage": NaN, "year": 2019.0}, {"cost": NaN, "coverage": NaN, "year": 2020.0}]', 'pars': '[{"active": true, "pops": ["tot"], "param": "numcirc"}]', 'criteria': '{"hivstatus": "allstates", "pregnant": false}', 'active': False, 'project_id': u'aff4843c-fd6a-11e5-bb5e-4fdb70cfcfcd', 'progset_id': u'b063b488-fd6a-11e5-bb5e-bf46bed73576'}
```

**Comment by boscoh** [comment]
Great writeup. Will have a look at it soon.

**Comment by cliffckerr** [comment]
@boscoh this seems to be a problem with converting things to json unnecessarily...so may not be easy to fix since the fix might be to blob everything in the database

**Comment by robynstuart** [comment]
Pls see https://drive.google.com/folderview?id=0BysN_-IUZuYBRFlDb2liZFVTdUE&usp=sharing for an example of a .prj file that produces this error

**Comment by robynstuart** [comment]
addressed for the time being by https://github.com/optimamodel/Optima/pull/773
