### ISSUE TITLE
Selecting any program gives the same error

### ISSUE THREAD

**Issue by boscoh** [optimamodel/Optima#779]
```
Traceback (most recent call last):
  File "/opt/optima/server/webapp/utils.py", line 63, in _report_exception
    return api_call(*args, **kwargs)
  File "/opt/optima/server/webapp/resources/project_progsets.py", line 352, in get
    result_instance = result_entry.hydrate()  # TODO raise exception if none
AttributeError: 'NoneType' object has no attribute 'hydrate'

```

**Comment by boscoh** [comment]
Fixed in https://github.com/optimamodel/Optima/pull/778
