### ISSUE TITLE
Automatic Calibration error

### ISSUE THREAD

**Issue by Rowanmh** [optimamodel/Optima#800]
Testing with Zimbabwe_femalePartnershipsFix_20160516.prj

After selecting a parameter set "testing new param" and clicking on start to run auto-fit, I got the following error:

```
Traceback (most recent call last):
  File "/opt/optima/server/webapp/utils.py", line 67, in _report_exception
    return api_call(*args, **kwargs)
  File "/opt/optima/server/webapp/resources/project_parsets.py", line 545, in post
    run_autofit.delay(project_id, parset_name, args['maxtime'])
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 453, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 565, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 354, in send_task
    reply_to=reply_to or self.oid, **options
  File "/usr/local/lib/python2.7/dist-packages/celery/app/amqp.py", line 305, in publish_task
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/kombu/messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 436, in _ensured
    return fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kombu/messaging.py", line 188, in _publish
    mandatory=mandatory, immediate=immediate,
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/virtual/__init__.py", line 521, in basic_publish
    message, exchange, routing_key, **kwargs
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/virtual/exchange.py", line 60, in deliver
    for queue in _lookup(exchange, routing_key):
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/virtual/__init__.py", line 612, in _lookup
    self.get_table(exchange),
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 753, in get_table
    raise InconsistencyError(NO_ROUTE_ERROR.format(exchange, key))
InconsistencyError: 
Cannot route message for exchange 'celery': Table empty or key no longer exists.
Probably the key ('_kombu.binding.celery') has been removed from the Redis database.
```

'celery' huh?

Trying on a different parameter set afterwards gives a message:  "automatic calibration already running." so it's still doing something in the background (and for more than the stipulated 10 seconds I'll note), even after opening a different project (which gave the same error) and swapping back, I can't even attempt another automatic calibration.

**Comment by boscoh** [comment]
I've seen this bug. I have no idea how to debug this as StarterSquad controls the server that deploys staging and I don't have access to that server. It may be of little solace to say that it works on my mac. I will have to setup a new server to debug this.

**Comment by boscoh** [comment]
After googling, I found someone who reported this same error and traced it to a hacked redis database. I wonder if this is the problem on the SSQ server? https://github.com/celery/kombu/issues/236
