### ISSUE TITLE
Uploading Spreadsheet Error

### ISSUE THREAD

**Issue by Rowanmh** [optimamodel/Optima#814]
Working on Armenia_20160520  (converted using latest script)
Downloaded data spreadsheet and filled with data from Optima 1.0
Attempted to upload spreadsheet for future consistency and less reliance on 1.0 files and generated the following error:

```
Traceback (most recent call last):
  File "/opt/optima/server/webapp/utils.py", line 67, in _report_exception
    return api_call(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 679, in wrapper
    resp = f(*args, **kwargs)
  File "/opt/optima/server/webapp/resources/project.py", line 443, in post
    project_instance.loadspreadsheet(server_filename)
  File "/opt/optima/optima/project.py", line 111, in loadspreadsheet
    self.data = loadspreadsheet(filename, verbose=self.settings.verbose) # Do the hard work of actually loading the spreadsheet
  File "/opt/optima/optima/loadspreadsheet.py", line 223, in loadspreadsheet
    else:                  validatedata(thesedata, sheetname, thispar, row, checkblank=(blh=='best'))
  File "/opt/optima/optima/loadspreadsheet.py", line 65, in validatedata
    raise OptimaException(errormsg)
OptimaException: No data or assumption entered for sheet "Population size", parameter "popsize", row=3
```

It looks like it doesn't want to allow incomplete population information for some years, which should be allowed (?).  Spreadsheet I'm trying to upload attached:

[Armenia_20160520.xlsx](https://github.com/optimamodel/Optima/files/273881/Armenia_20160520.xlsx)

**Comment by Rowanmh** [comment]
Err, nevermind...

I copied the data across and hadn't saved the file, fair enough that it was generating that error!
