### ISSUE TITLE
Error uploading converted Kenya project

### ISSUE THREAD

**Issue by Rowanmh** [optimamodel/Optima#819]
```
Traceback (most recent call last):
  File "/opt/optima/server/webapp/utils.py", line 67, in _report_exception
    return api_call(*args, **kwargs)
  File "/opt/optima/server/webapp/resources/project.py", line 771, in post
    project_record.restore(project)
  File "/opt/optima/server/webapp/dbmodels.py", line 294, in restore
    progset_record.restore(progset, program_summaries)
  File "/opt/optima/server/webapp/dbmodels.py", line 730, in restore
    update_or_create_program_record(self.project.id, self.id, short, program_summary, active)
  File "/opt/optima/server/webapp/utils.py", line 459, in update_or_create_program_record
    .filter_by(short=short, project_id=project_id, progset_id=progset_id)\
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2367, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2228, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2437, in __iter__
    self.session._autoflush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1208, in _autoflush
    util.raise_from_cause(e)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1198, in _autoflush
    self.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1919, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2001, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 602, in _emit_insert_statements
    execute(statement, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
DataError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (DataError) invalid input syntax for type json
LINE 1: ...vstatus": "allstates", "pregnant": false}', '[]', '{"saturat...
                                                             ^
DETAIL:  Token "Infinity" is invalid.
CONTEXT:  JSON data, line 1: ...1.0, 1.0]], "t": [2016.0], "unitcost": [[Infinity...
 'INSERT INTO programs (progset_id, project_id, category, name, short_name, pars, active, targetpops, criteria, costcov, ccopars, created, updated) VALUES (%(progset_id)s, %(project_id)s, %(category)s, %(name)s, %(short_name)s, %(pars)s, %(active)s, %(targetpops)s, %(criteria)s, %(costcov)s, %(ccopars)s, %(created)s, %(updated)s) RETURNING programs.id' {'category': 'Care and treatment', 'updated': datetime.datetime(2016, 5, 21, 18, 32, 55, 93436, tzinfo=tzutc()), 'name': 'Orphans and vulnerable children', 'short_name': 'OVC', 'created': datetime.datetime(2016, 5, 21, 18, 32, 55, 93354, tzinfo=tzutc()), 'ccopars': '{"saturation": [[1.0, 1.0]], "t": [2016.0], "unitcost": [[Infinity, Infinity]]}', 'targetpops': [], 'costcov': '[]', 'pars': '[]', 'criteria': '{"hivstatus": "allstates", "pregnant": false}', 'active': True, 'project_id': u'6e01002a-1f82-11e6-bbc3-a72a4763204a', 'progset_id': u'6f058446-1f82-11e6-bbc3-4b43165d67a7'}
```

Any ideas @robynstuart or @boscoh ?  FE error or conversion problem?

**Comment by Rowanmh** [comment]
Similar for Malawi:

```
Traceback (most recent call last):
  File "/opt/optima/server/webapp/utils.py", line 67, in _report_exception
    return api_call(*args, **kwargs)
  File "/opt/optima/server/webapp/resources/project.py", line 771, in post
    project_record.restore(project)
  File "/opt/optima/server/webapp/dbmodels.py", line 294, in restore
    progset_record.restore(progset, program_summaries)
  File "/opt/optima/server/webapp/dbmodels.py", line 730, in restore
    update_or_create_program_record(self.project.id, self.id, short, program_summary, active)
  File "/opt/optima/server/webapp/utils.py", line 459, in update_or_create_program_record
    .filter_by(short=short, project_id=project_id, progset_id=progset_id)\
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2367, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2228, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2437, in __iter__
    self.session._autoflush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1208, in _autoflush
    util.raise_from_cause(e)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1198, in _autoflush
    self.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1919, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2001, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 602, in _emit_insert_statements
    execute(statement, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
DataError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (DataError) invalid input syntax for type json
LINE 1: ...859957428, "coverage": 8534.0, "year": 2011.0}]', '{"saturat...
                                                             ^
DETAIL:  Token "Infinity" is invalid.
CONTEXT:  JSON data, line 1: ...75, 0.75]], "t": [2016.0], "unitcost": [[Infinity...
 'INSERT INTO programs (progset_id, project_id, category, name, short_name, pars, active, targetpops, criteria, costcov, ccopars, created, updated) VALUES (%(progset_id)s, %(project_id)s, %(category)s, %(name)s, %(short_name)s, %(pars)s, %(active)s, %(targetpops)s, %(criteria)s, %(costcov)s, %(ccopars)s, %(created)s, %(updated)s) RETURNING programs.id' {'category': 'Prevention', 'updated': datetime.datetime(2016, 5, 21, 18, 37, 14, 800967, tzinfo=tzutc()), 'short_name': 'VMMC', 'costcov': '[{"cost": 7681672.988372093, "coverage": 34000.0, "year": 2004.0}, {"cost": 6565249.859957428, "coverage": 8534.0, "year": 2011.0}]', 'created': datetime.datetime(2016, 5, 21, 18, 37, 14, 800871, tzinfo=tzutc()), 'ccopars': '{"saturation": [[0.75, 0.75]], "t": [2016.0], "unitcost": [[Infinity, Infinity]]}', 'targetpops': ['Clients', 'MSM', 'Males 0-14', 'Males 15-24', 'Males 25-49', 'Males 50+'], 'pars': '[{"active": true, "pops": ["Clients", "MSM", "Males 0-14", "Males 15-24", "Males 25-49", "Males 50+"], "param": "numcirc"}]', 'criteria': '{"hivstatus": "allstates", "pregnant": false}', 'active': True, 'project_id': u'08f368c0-1f83-11e6-b8f1-938538348636', 'progset_id': u'09d95ed4-1f83-11e6-b8f1-976d40fae9f0', 'name': 'Voluntary medical male circumcision'}
```

**Comment by Rowanmh** [comment]
Also Moldova Left and Right Bank have the same kind of error but looks like OST is the program at fault.

All of the other currently converted projects (which is all of them except those with the negative people error) upload okay.

**Comment by sherriekelly** [comment]
Robyn working on this next (24 May 2016, 5:00pm Sydney time)

**Comment by robynstuart** [comment]
Fixed in https://github.com/optimamodel/Optima/pull/822

**Comment by sherriekelly** [comment]
Great, thanks.
